version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - run:
          name: "test variable"
          command: echo $variableTest
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: npm install